
version: '3.7'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    container_name: logstash
    volumes:
      -  /var/lib/docker/volumes/three-node-cluster-6-4-2-aws_es-logs-one/_data:/var/eslogs
    secrets:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
      #- source: logstash.yml
        #target: /usr/share/logstash/config/logstash.yml
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    container_name: filebeat
    user: root
    privileged: true
    command: --strict.perms=false -e
    volumes:
      -  /home/ubuntu/file-log:/var/file-log
    secrets:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5
secrets:
  filebeat.yml:
    file: ./filebeat.yml
  #logstash.yml:
    #file: ./logstash.yml
  logstash.conf:
    file: ./pipeline/logstash.conf
