version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - node.name=vibhuvi-l-node
      - discovery.type=single-node
      - cluster.name=vibhuvi-l-es-data-cluster
      - bootstrap.memory_lock=true
      - xpack.enabled="true"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - vibhuvi-lesdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
      ELASTICSEARCH_HOSTS: elasticsearch:9200
    networks:
      - elastic
networks:
  elastic:
    external:
      name: elastic
volumes:
  vibhuvi-lesdata:
    driver: local
