version: "3.7"

services:

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.7.0
    hostname: "ElasticsearchMetricbeat"
    container_name: metricbeat
    user: root
    networks:
      - elastic
    configs:
      - source: mb_config
        target: /usr/share/metricbeat/metricbeat.yml
    volumes:
      - metricbeat:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
    # disable strict permission checks
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    deploy:
      mode: global

networks:
  elastic:
    external:
      name: elastic
volumes:
  metricbeat:

configs:
  mb_config:
    file: ./metricbeat-conf.yml
