version: '3'
services:
  main:
    image: jenkinsci/jenkins:${TAG:-lts-alpine}
    ports:
      - ${UI_PORT:-8080}:8080
      - ${AGENTS_PORT:-50000}:50000
    # environment:
    #   - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
      
volumes:
  jm:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/db/jenkins/home/
  jmshare:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/db/jenkins/share/    
