version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports: ["9200:9200"]
    environment:
      cluster.name: "monitoring-cluster"
      node.name: "es-node-one"
      network.host: 0.0.0.0
      transport.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      xpack.license.self_generated.type: basic
      xpack.monitoring.history.duration: 7d
      xpack.monitoring.collection.enabled: "true"
      xpack.monitoring.collection.interval: 60s
      script.painless.regex.enabled: "true"
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    healthcheck:
      test: curl -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  es_data:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /var/db/wisestep/monitoring-elasticsearch/data
