version: '3'
services:
  metasploit:
    image: metasploitframework/metasploit-framework:latest
    container_name: metasploit
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf?pool=200&timeout=5
    links:
      - db
    ports:
      - 4444:4444
    # volumes:
    #   - ./.msf4:/home/msf/.msf4

  db:
    image: postgres:10-alpine
    container_name: postgres
    restart: always
    environment:
      # POSTGRES_DB: msdb
      # POSTGRES_USER: msuser
      # POSTGRES_PASSWORD: msuser
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  pg_data:
    driver: local