version: "3.7"
services:
  cassandra-one:
    image: cassandra:3.9
    container_name: cassandra
    # volumes:
    #     - cassandra-volume:/var/lib/cassandra/
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_CLUSTER_NAME='sample-cluster'
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=sample-datacenter-one
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    restart: always
# volumes:
#   cassandra-volume:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /root/db/cassandra-volume/
