version: "3"
services:
   gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    # hostname: ${GITLAB_HOSTNAME}
    container_name: gitlab
    env_file:
     - ./.env
    # environment:
    #   GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
        # gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # external_url 'http://gitlab.example.com:9090'
    ports:
      - '80:80'
      - '443:443'
      # - '22:22'
      # - '9090:9090' # publish when external_url 'http://gitlab.example.com:9090'
      # - '2224:22' # publish when gitlab_rails['gitlab_shell_ssh_port'] = 2224
      # - 198.51.100.1:443:443 # you can publish on the IP
      # - 198.51.100.1:80:80
      # - 198.51.100.1:22:22
    volumes:
      - './data/gitlab/config:/etc/gitlab'
      - './data/gitlab/logs:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'
