metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
 
xpack.monitoring.enabled: true
setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "http"

setup.kibana:
  host: "http://kibana:5601"
  protocol: "http"
  ssl.enabled: false

metricbeat.modules:
- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    - index_summary
    - shard
  period: 20s
  hosts: ["http://192.168.0.8:9200"]
  # hosts: ["http://192.31.2.66:9200", "http://192.31.3.66:9200", "http://192.31.4.66:9200"]
  # xpack.enabled: true
