version: '3.7'
services:
  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - "./logs/nginx:/var/log/nginx"
    restart: always
    ports: ["80:80"]
