version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports: 
      - "8080:8080"
      - "50000:50000"
    networks:
      - cicd
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
volumes:
  jenkins_home:
networks:
  cicd: