version: '3.7'
services:
  redis:
    image: redis:6
    container_name: redis_master
    command: ["redis-server", "--appendonly", "yes", "--bind", "0.0.0.0"]
    ports: ["6379:6379"]
    networks:
      vibhuvi_network_redis:
  sentinel:
    image: redis:6
    container_name: sentinel
    user: root
    privileged: true
    ports: ["26379:6379"]
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf
    command: redis-server /etc/sentinel.conf --sentinel
    networks:
      vibhuvi_network_redis:
networks:
  vibhuvi_network_redis: