version: '3'
services:
    cassandra:
        image: cassandra:3.9
        restart: unless-stopped
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint.sh
            - /var/db/cassandra:/var/lib/cassandra
            - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160