version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    restart: unless-stopped
    container_name: elasticsearch
    environment:
      - cluster.name=elastic-test
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/elasticsearch/data:/usr/share/elasticsearch/data
    ports: ["9200:9200", "9300:9300"]
    networks: ["skills_api_network"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports: ["5601:5601"]
    networks: ["skills_api_network"]
networks:
  skills_api_network:
    external:
      name: dev_default
      
