version: '3'
services:
  postgres:
    image: postgres:9.6
    c
  arachni:
    image: arachni/arachni:latest
    container_name: arachni
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: postgres
      DB_NAME: arachni
      DB_USER: test_username
      DB_PASS: test_username
    ports:
      - "7331:7331"
      - "9292:9292"
      - "222:22"
    depends_on:
      - postgres
