version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./certs:/etc/nginx/ssl:ro"
      - "./html:/usr/share/nginx/html:ro"
      - "./logs/nginx:/var/log/nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
