cat <<EOF >> docker-compose.yml
version: '3.7'
services:
  redis-two:
    image: redis:6
    container_name: redis_replica_one
    command: ["redis-server", "--appendonly", "yes", "--bind", "0.0.0.0"]
    ports: ["6379:6379"]
    networks:
      vibhuvi_network_redis:
  sentinel-two:
    image: redis:6
    container_name: sentinel_two
    ports: ["26379:6379"]
    volumes:
      - ./sentinel-two.conf:/etc/sentinel.conf
    command: redis-server /etc/sentinel.conf --sentinel
    networks:
      vibhuvi_network_redis:
networks:
  vibhuvi_network_redis:
EOF