version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium_hub
    ports: ["4444:4444"]
    networks: ["grid"]
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
  node-chrome:
    image: selenium/node-chrome
    container_name: node_chrome
    networks: ["grid"]
    ports:  ["9001:5900"]
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes: ["/dev/shm:/dev/shm"]  
networks:
  grid:
