version: '3.7'
volumes:
  minio_data: 
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /var/db/minio/data
services:
  minio:
    image: minio/minio:RELEASE.2020-01-25T02-50-51Z
    ports:
      - '9000:9000'
    container_name: minio
    volumes:
      - 'minio_data:/data'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
