version: '3.1'

services:
  minio1:
    image: minio/minio:RELEASE.2017-11-22T19-55-46Z
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints: [node.hostname == HEPC-UHDH-VM18]
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:RELEASE.2017-11-22T19-55-46Z
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints: [node.hostname == HEPC-UHDH-VM19]
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio3:
    image: minio/minio:RELEASE.2017-11-22T19-55-46Z
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints: [node.hostname == HEPC-UHDH-VM20]
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

  minio4:
    image: minio/minio:RELEASE.2017-11-22T19-55-46Z
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - minio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints: [node.hostname == HEPC-UHDH-VM20]
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    secrets:
      - secret_key
      - access_key

volumes:
  minio1-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/minioonedata/
  minio2-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/miniotwodata/
  minio3-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/miniothreedata/
  minio4-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /root/miniofourdata/
networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true