heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://elasticsearch:9200
    - http://kibana:5601
    - https://google.com
    - https://github.com
    - https://wisestep.com
    - https://recruiter.wisestep.com
 
- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_cloud_metadata:
- add_observer_metadata:
    cache.ttl: 5m
    geo:
      name: nyc-dc1-rack1
      location: 40.7128, -74.0060
      continent_name: North America
      country_iso_code: US
      region_name: New York
      region_iso_code: NY
      city_name: New York
output.elasticsearch:
  hosts: ['elasticsearch:9200']
 
setup.kibana:
  host: "http://kibana:5601"
 
xpack.monitoring.enabled: true
